import Footer from "@/components/Footer/Footer";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;
import "./globals.css";
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'], // Spécifiez les poids nécessaires
  display: 'swap',
});

export const metadata = {
  title: "Les petits plats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={inter.className}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
